DjangoBlog/DjangoBlog/urls.py
from django.contrib import admin
from django.urls import path,include
#增加站点地图
from django.contrib.sitemaps.views import sitemap
from .sitemap import StaticViewSitemap,ArticleSiteMap,CategorySiteMap,TagSiteMap,UserSiteMap
from .feeds import DjangoBlogFeed
from django.views.decorators.cache import cache_page
from django.conf import settings
from django.conf.urls.static import static

sitemaps ={
        'blog':ArticleSiteMap,
        'Category':CategorySiteMap,
        'Tag':TagSiteMap,
        'User':UserSiteMap,
        'static':StaticViewSitemap,
        }


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blog.urls',namespace ='blog')),
    #增加评论url
    path('',include('comments.urls',namespace='comments')),
    #账号相关url
    path('',include('accounts.urls',namespace='accounts')),
    path('',include('oauth.urls',namespace='oauth')),
    path('sitemap.xml',cache_page(60*60*10)(sitemap),{'sitemaps':sitemaps},name='django.contrib.sitemaps.views.sitemap'),
    path('feed/',cache_page(60*60*10)(DjangoBlogFeed())),
    #添加搜索相关功能
    path('search',include('haystack.urls'),name='search'),
    ] + static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

DjangoBlog/accounts/urls.py
#!/usr/bin/env python
#encoding:utf-8
from django.urls import path
from .forms import LoginForm
from django.contrib.auth import views as auth_view
from . import views
app_name ='accounts'
urlpatterns =[
        path('login/',views.LoginView.as_view(success_url='/'),name='login',kwargs={'authentication_form':LoginForm}),
        path('register/',views.RegisterView.as_view(success_url='/'),name='register'),
        path('logout/',views.LogoutView.as_view(),name='logout')
        ]

DjangoBlog/blog/urls.py
from django.urls import path
from . import views
from haystack.forms import ModelSearchForm
from haystack.query import SearchQuerySet
from haystack.views import SearchView
from django.views.decorators.cache import cache_page

#如果引用blog的url使用的include中指定了namespace则必须定义app_name或者在include中指定app_name
app_name ='blog'
urlpatterns  =[
    path('',views.IndexView.as_view(),name='index'),
    path('page/<page>',views.IndexView.as_view(),name='index_page'),
    path('article/<year>/<month>/<day>/<article_id>-<slug>.html',views.ArticleDetailView.as_view(),name = 'detailbyid'),
    path('category/<category_name>',views.CategoryDetailView.as_view(),name ='category_detail'),
    path('author/<author_name>',views.AuthorDetailView.as_view(),name='author_detail'),
    path('tags/<tag_name>',views.TagDetailView.as_view(),name='tag_detail'),
    path('blogpage/<year>/<month>/<day>/<page_id>-<slug>.html',views.ArticleDetailView.as_view(),name ='pagedetail'),
    path('upload',views.fileupload,name='upload'),
    path('refresh',views.refresh_memcache,name='refresh')
    ]

DjangoBlog/blog/forms.py
#!/usr/bin/env python
#encoding:utf-8
from haystack.forms import SearchForm
from django import forms
from .models import Article,Category
class BlogSearchForm(SearchForm):
    querydata = forms.CharField(required = True)


    def search(self):
        datas = super(BlogSearchForm,self).search()

        if not self.is_valid():
            return selfno_query_found()

        if self.cleaned_data['querydata']:
            print(self.cleaned_data['querydata'])

        return datas    

DjangoBlog/blog/views.py
from django.shortcuts import render
from blog.models import Article,Category,Tag
# Create your views here.
#View 视图主要使用Model 的模型
from django.views.generic.list import  ListView
from django.views.generic import TemplateView
from django.views.decorators.cache import cache_page
from django.views.generic.detail import DetailView
from django.conf import settings
from django.core.exceptions import ObjectDoesNotExist
#通用显示视图
#调试调用栈
import traceback
#评论相关
from django.views.generic import UpdateView
from comments.forms import CommentForm
from comments.models import Comment
from django.core.paginator import Paginator,PageNotAnInteger,EmptyPage
from django.conf import settings
from django import forms
from abc import ABCMeta,abstractmethod
from haystack.generic_views import SearchView
from blog.forms import BlogSearchForm
import datetime
from django.views.decorators.csrf import csrf_exempt
import os
from django.contrib.auth.decorators import login_required
from DjangoBlog.utils import cache,cache_decorator,logger,get_md5
from django.utils.cache import get_cache_key
from django.utils.decorators import method_decorator
from django.utils.decorators import classonlymethod
from django.http import HttpResponseRedirect
"""class SeoProcessor():
    __metaclass__ = ABCMeta

    @abstractmethod
    def get_title(self):
        pass
    
    @abstractmethod
    def get_keywords(self):
        pass

    @abstractmethod
    def get_description(self):
        pass
"""
"""class CacheTemplateView(ListView):
    @classonlymethod
    def as_view(cls,**initkwargs):
        view = super(CacheTemplateView,cls).as_view(**initkwargs)
        return cache_page(60*60*10)(view)
"""
class ArticleListView(ListView):
    #template_name 属性用于指定用哪个模板进行渲染
    template_name = 'blog/article_index.html'
    #context_object_name 用于给上下文变量取名（模板中使用）
    context_object_name   = 'article_list'
    #页面类型
    page_type =  ''
    paginate_by = settings.PAGINATE_BY
    page_kwarg ='page'
    print("ArticleListView() constructor")
    
    def get_view_cache_key(self):
        return self.request.get['pages']

    @property
    def page_number(self):
        page_kwarg = self.page_kwarg
        page = self.kwargs.get(page_kwarg) or self.request.GET.get(page_kwarg) or 1
        return page

    def get_queryset_cache_key(self):
        """
        子类重写，获得queryset的缓存key
        """
        raise  NotImplementedError()
    
    def get_queryset_data(self):

        raise NotImplementedError()

    def get_queryset_from_cache(self,cache_key):
        value =cache.get(cache_key)
        if value:
            logger.info('get view cache.key:{key}'.format(key=cache_key))
            return value
        else:
            article_list = self.get_queryset_data()
            cache.set(cache_key,article_list)
            logger.info('set view cache.key:{key}'.format(key=cache_key))
            return article_list

    def get_queryset(self):
        key = self.queryset_cache_key()
        value = self.get_queryset_from_cache(key)
        return value


    def __init__(self):
        print("ArtilceListView() __init__()")
        self.page_description =  ''

class IndexView(ArticleListView):
    print("Index() constructor")
    #template_name属性用于指定用哪个模板进行渲染
    #template_name = 'index.html'


    #context_object_name属性用于给上下文变量取名（在模板中使用该名字)
    #context_object_name = 'article_list'


    #get_queryset是覆盖ListView的方法,由父类调用
    def get_queryset(self):
        print("IndexView get_queryset() enter")
        article_list = Article.objects.filter(type='a',status='p')
        #for article in article_list:0
        #    article.body = article.body[0:settings.ARTICLE_SUB_LENGTH]

        return article_list
    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        print("get_context_data() enter")
        return context
    
    def get_queryset_data(self):
       article_list = Article.objects.filter(type='a',status='p')
       return article_list

    def get_queryset_cache_key(self):
       cache_key  =  'index_{page}'.format(page=self.page_number)
       return cache_key

class ArticleDetailView(DetailView):
    print("ArticleDetailView() enter")
    template_name =  'blog/article_detail.html'
    model = Article
    pk_url_kwarg = 'article_id'
    context_object_name  = "article"

    def get_object(self):
        print("ArticleDetailView get_object() enter")
        obj = super(ArticleDetailView,self).get_object()
        obj.viewed()
        self.object = obj
        return obj
    
    def dispatch(self,request,*args,**kwargs):
        slug = self.kwargs['slug'] if 'slug' in self.kwargs else ''
        if slug:
            obj = super(ArticleDetail,self).get_object()
            return HttpResponseRedirect(obj.get_absolute_url)
        else:
            return super(ArticleDetailView,self).dispatch(request,*args,**kwargs)

    #重写get_context_data
    def get_context_data(self,**kwargs):
        artilceid = int(self.kwargs[self.pk_url_kwarg])
        
        #评论相关
        comment_form = CommentForm()
        u = self.request.user
        if self.request.user.is_authenticated:
            comment_form.fields.update({'email':forms.CharField(widget=forms.HiddenInput()),'name':forms.CharField(widget=forms.HiddenInput()),})
            user = self.requst.user
            comment_form.fields['email'].initial  = user.email
            comment_form.fields['name'].initial  = user.username
        key ="article_comment_{}".format(articleid)
        
        article_comments = self.object.comment_list()
        print(article_comments)

        kwargs['form']  = comment_form
        kwargs['article_comments'] = article_comments
        kwargs['comment_count'] = len(article_comments) if article_comments else 0;
        #评论相关
        
        kwargs['next_article']  = self.object.next_article
        kwargs['pre_article'] = self.object.pre_article

        return super(ArticleDetail,self).get_context_data(**kwargs)

class CategoryDetailView(ArticleListView):
    print("CategoryDetailView constructor")
    page_type  ="分类目录归档"
    

    def get_queryset_data(self):
        slug  = self.kwargs['category_name']
        category = get_object_or_404(Category,slug=slug)
        categoryname = category.name
        self.categoryname = categoryname
        categorynames = list(map(lambda c:c.name,category.get_sub_categorys()))
        article_list = Article.objects.filter(category__name__in =categorynames,status='p')
        return article_list

    
    def get_queryset_cache_key(self):
        slug = self.kwargs['category_name']
        category =get_object_or_404(Category,slug=slug)
        categoryname =category.name
        self.categoryname =categoryname
        cache_key ='category_list_{categoryname}_{page}'.format(categoryname=cateforyname,page=self.page_number)
        return cache_key

    def get_queryset(self):
        slug = self.kwargs['category_name']
        category= Category.objects.get(slug=slug)
        categoryname = category.name
        self.categoryname = categoryname
        print("CateGoryDetailView get_queryset() enter")
        try:
            categoryname = categoryname.split('/')[-1]
        except:
            pass
        article_list = Article.objects.filter(category__name=categoryname,status='p')
        return article_list
    
    def get_context_data(self,**kwargs):
        #增加额外数据
        print("CategoyDetailView get_context_data() enter")
        categoryname = self.categoryname
        try:
            categoryname = categoryname.split('/')[-1]
        except:
            pass
        kwargs['page_type'] =CategoryDetailView.page_type
        kwargs['tag_name'] = categoryname
        return super(CategoryDetailView,self).get_context_data(**kwargs)

class AuthorDetailView(ArticleListView):
    page_type = '作者文章归档'
    print("AuthorDetailView constructor")
    
    def get_queryset_cache_key(self):
        author_name  = self.kwargs['author_name']
        cache_key = 'author_{author_name}_{page}'.fromat(author_name=author_name,page=self.page_number)
        return cache_key

    def get_queryset_data(self):
        print("AuthorDetailView get_queryset_data()")
        author_name = self.kwargs['author_name']
        article_list = Article.objects.filter(author__username=author_name)
        return article_list
    
    def get_context_data(self,**kwargs):
        author_name = self.kwargs['author_name']
        kwargs['page_type'] =AuthorDetailView.page_type
        kwargs['tag_name'] = author_name
        return super(AuthorDetailView,self).get_context_data(**kwargs)

class TagListView(ListView):
    print("TagListView constructor")
    template_name = ''
    context_object_name =  'tag_list'

    def get_queryset(self):
        print("TagListView get_query_set() enter")
        tags_list = []
        tags = Tag.objects.all()
        for t in tags:
            t.article_set.count()

class TagDetailView(ArticleListView):
    page_type ='分类标签归档'
    print("TagDetailView constrouctor")
    def get_queryset_data(self):
        print("TagDetailView get_queryset() enter")
        slug = self.kwargs['tag_name']
        tag = get_object_or_404(Tag,slug=slug)
        tag_name = tag.name
        self.name = tag_name
        article_list = Article.objects.filter(tags__name = tag_name)
        return article_list

    def get_queryset_cache_key(self):
        slug = self.kwargs['tag_name']
        tag = get_object_or_404(Tag,slug=slug)
        tag_name = tag.name
        self.name  =tag_name
        cache_key = 'tag_{tag_name}_{page}'.format(tag_name=tag_name,page=self.page_number)
        return cache_key

    def get_context_data(self,**kwargs):
      print("TagDetailView get_context_data()")
      tag_name = self.name
      kwargs['page_type'] = TagDetailView.page_type
      kwargs['tag_name'] = tag_name
      return super(TagDetailView,self).get_context_data(**kwargs)


#文件上传功能
@csrf_exempt
def fileupload(request):

DjangoBlog/templates/blog/article_detail.html
{% extends 'share_layout/base.html' %}
{% load blog_tags %}
{% block header %}
 <title>{{ article.title }} | {{ SITE_DESCRIPTION }}</title>
    <meta property="og:type" content="article"/>
    <meta property="og:title" content="{{ article.title }}"/>
    <meta property="og:description" content="{{  article.body|custom_markdown|striptags|truncateword:20 }}"/>
    <meta property="og:url"
          content="{{ article.get_full_url }}"/>
    <meta property="article:published_time" content="{% datetimeformat article.pub_time %}"/>
    <meta property="article:modified_time" content="{% datetimeformat article.pub_time %}"/>
    <meta property="article:author" content="{{ article.author.get_full_url }}"/>
    <meta property="article:section" content="{{ article.category.name }}"/>
    {% for t in article.tags.all %}
        <meta property="article:tag" content="{{ t.name }}"/>
    {% endfor %}
    <meta property="og:site_name" content="{{ SITE_NAME }}"/>
{% endblock  %}
{% block content %}
<script>console.log("这里是articledetail.html");</script>
    <div id="primary" class="site-content">
        <div id="content" role="main">
            {% load_article_detail article False user %}
	     {% if article.type == 'a'%}
            <nav class="nav-single">
                <h3 class="assistive-text">文章导航</h3>
                {% if next_article %}

                    <span class="nav-previous"><a href="{{ next_article.get_absolute_url }}" rel="prev"><span
                            class="meta-nav">&larr;</span> {{ next_article.title }}</a></span>
                {% endif %}
                {% if prev_article %}
                    <span class="nav-next"><a href="{{ prev_article.get_absolute_url }}"
                                              rel="next">{{ prev_article.title }} <span
                            class="meta-nav">&rarr;</span></a></span>
                {% endif %}
            </nav><!-- .nav-single -->
	    {%  endif %}
	    </div>
            {% if article.commentstatus == "o" %}
	    {% comment %} {% load comments_tags %}  
	    {% load_post_comment article from %} {% endcomment%}
	    {% include 'comments/tags/comment_list.html' %}
	    {% if user.is_authenticated %}
	    	{% include 'comments/tags/post_comment.html' %}
	    {% else %}
	    	<div class="comment-area">
			<h3 class ="comment-area">你还没登录，请您<a href="{% url  "account:login" %}">登录</a></h3>
			{% load oauth-tags  %}
			{% load_auth_applications %}
		</div>
            {% endif %}
    </div><!-- #primary -->
{% endblock %}


{% block sidebar %}
{% load_sidebar user %}
{% endblock %}

DjangoBlog/templates/blog/article_index.html
{% extends 'share_layout/base.html' %}
{% load blog_tags %}
{% load cache %}
{% block header %}
{% if tag_name  %}
    <title>{{ page_type}}:{{ tag_name }} | {{ SITE_DESCRIPTION }}</title>
    {% comment %} <meta name="description" content="{{page_type}}:{{tag_name}}"/> {% endcomment%}
    {% else %}
    <title>{{  SITE_NAME  }}|{{ SITE_DESCRIPTION }}</title>
    {% endif  %}
    <meta name="description" content="{{ SITE_SEO_DESCRIPTION }}"/>
    <meta name="keywords" content="{{ SITE_SEO_KEYWORDS }}"/>
    <meta property="og:type" content="blog"/>
    <meta property="og:title" content="{{ SITE_NAME }}"/>
    <meta property="og:description" content="{{ SITE_DESCRIPTION }}"/>
    <meta property="og:url" content="{{ SITE_BASE_URL }}"/>
    <meta property="og:site_name" content="{{ SITE_NAME }}"/>
{%  endblock  %}
{% block content %}
<script>console.log("这里是index.html");</script>
    <div id="primary" class="site-content">
        <div id="content" role="main">
	    <script>console.log("触发arrticle_list查询")</script>
	    {% if page_type  and  tag_name %}
	    <header class="archive-header">
	    <h1 class="archive-title">{{ page_type }}：<span>{{ tag_name }}</span></h1>
            </header><!-- .archive-header -->
            	{% endif %}
		{% for article in article_list  %}
			{% load_article_detail article True  user %}
            {% endfor %}

	    {% if is_paginated %}
	    {% load_pagination_info page_obj page_type tag_name %}
	    {% comment %}<nav id="nav-below" class="navigation" role="navigation">
                    <h3 class="assistive-text">文章导航</h3>
                    {% if page_obj.has_next %}
                        <div class="nav-previous"><a
                                href="{{ SITE_BASE_URL }}page/{{ page_obj.next_page_number }}"><span
                                class="meta-nav">&larr;</span> 早期文章</a></div>
                    {% endif %}
                    {% if page_obj.has_previous %}
                        <div class="nav-next"><a href="{{ SITE_BASE_URL }}page/{{ page_obj.previous_page_number }}">较新文章
                            <span
                                    class="meta-nav">→</span></a>
                        </div>
                    {% endif %}
	    </nav><!-- .navigation -->{% endcomment %}
            {% endif %}
	 </div><!-- #content -->
    </div><!-- #primary -->
{% endblock %}


{% block sidebar %}
     <script>console.log("调用blog_tag的包含标签")</script>
    {% load_sidebar request.user %}
{% endblock %}

DjangoBlog/templates/blog/articledetail.html
{% extends 'base.html' %}
{% load blog_tags %}
{% block header %}
 <title>{{ article.title }} | {{ SITE_DESCRIPTION }}</title>
    <meta property="og:type" content="article"/>
    <meta property="og:title" content="{{ article.title }}"/>
    <meta property="og:url"
          content="{{ article.get_absolute_url }}"/>
    <meta property="article:published_time" content="{% datetimeformat article.pub_time %}"/>
    <meta property="article:modified_time" content="{% datetimeformat article.pub_time %}"/>
    <meta property="article:author" content="{{ article.author.get_absolute_url }}"/>
    <meta property="article:section" content="{{ article.category.name }}"/>
    {% for t in article.tags.all %}
        <meta property="article:tag" content="{{ t.name }}"/>
    {% endfor %}
    <meta property="og:site_name" content="{{ SITE_NAME }}"/>
{% endblock  %}
{% block content %}
<script>console.log("这里是articledetail.html");</script>
    <div id="primary" class="site-content">
        <div id="content" role="main">
            {% load_article_detail article False user %}

            <nav class="nav-single">
                <h3 class="assistive-text">文章导航</h3>
                {% if next_article %}

                    <span class="nav-previous"><a href="{{ next_article.get_absolute_url }}" rel="prev"><span
                            class="meta-nav">&larr;</span> {{ next_article.title }}</a></span>
                {% endif %}
                {% if prev_article %}
                    <span class="nav-next"><a href="{{ prev_article.get_absolute_url }}"
                                              rel="next">{{ prev_article.title }} <span
                            class="meta-nav">&rarr;</span></a></span>
                {% endif %}
            </nav><!-- .nav-single -->
	    </div>
            {% if article.commentstatus == "o" %}
	    {% comment %} {% load comments_tags %}  
	    {% load_post_comment article from %} {% endcomment%}
	    {% include 'comments/tags/comment_list.html' %}
	    {% include 'comments/tags/post_comment.html' %}
            {% endif %}
    </div><!-- #primary -->
{% endblock %}


{% block sidebar %}
{% load_sidebar user %}
{% endblock %}

DjangoBlog/templates/blog/articletaglist.html
{% if article_tags_list %}
<script>console.log("这里是articletaglist.html");</script>
    <div class="panel panel-default">
        <div class="panel-heading">标签</div>
        <div class="panel-body">

            {% for url,count,tag,color in article_tags_list %}
                <a class="label label-{{ color }}" style="display: inline-block;" href="{{ url }}"
                   title="{{ tag.name }}">
                    {{ tag.name }}
                    <span class="badge">{{ count }}</span>
                </a>
            {% endfor %}

        </div>
    </div>
{% endif %}

DjangoBlog/templates/blog/categorytree.html
<ol class="breadcrumb">
    {% for name,url in names %}
        <li>
            <a href="{{ url }}">
                {{ name }}
            </a>
        </li>
    {% endfor %}
</ol>

DjangoBlog/templates/blog/index.html
{% extends 'base.html' %}
{% load blog_tags %}
{% block header %}
    <title>{{ SITE_NAME }} | {{ SITE_DESCRIPTION }}</title>
    <meta name="description" content="{{ SITE_SEO_DESCRIPTION }}"/>
    <meta name="keywords" content="linux,apache,mysql,服务器,ubuntu,shell,java,web,javaweb,wordpress,csharp,.net,asp"/>
    <meta property="og:type" content="blog"/>
    <meta property="og:title" content="{{ SITE_NAME }}"/>
    <meta property="og:description" content="{{ SITE_DESCRIPTION }}"/>
    <meta property="og:url" content="{{ SITE_BASE_URL }}"/>
    <meta property="og:site_name" content="{{ SITE_NAME }}"/>
{%  endblock  %}
{% block content %}
<script>console.log("这里是index.html");</script>
    <div id="primary" class="site-content">
        <div id="content" role="main">
	    <script>console.log("触发arrticle_list查询")</script>
	    {% if page_type  and  tag_name %}
	    <header class="archive-header">
	    <h1 class="archive-title">{{ page_type }}：<span>{{ tag_name }}</span></h1>
            </header><!-- .archive-header -->
            	{% endif %}
		{% for article in article_list  %}
			{% load_article_detail article True  user %}
            {% endfor %}

	    {% if is_paginated %}
                <nav id="nav-below" class="navigation" role="navigation">
                    <h3 class="assistive-text">文章导航</h3>
                    {% if page_obj.has_next %}
                        <div class="nav-previous"><a
                                href="{{ SITE_BASE_URL }}page/{{ page_obj.next_page_number }}"><span
                                class="meta-nav">&larr;</span> 早期文章</a></div>
                    {% endif %}
                    {% if page_obj.has_previous %}
                        <div class="nav-next"><a href="{{ SITE_BASE_URL }}page/{{ page_obj.previous_page_number }}">较新文章
                            <span
                                    class="meta-nav">→</span></a>
                        </div>
                    {% endif %}
                </nav><!-- .navigation -->
            {% endif %}
	 </div><!-- #content -->
    </div><!-- #primary -->
{% endblock %}


{% block sidebar %}
     <script>console.log("调用blog_tag的包含标签")</script>
    {% load_sidebar request.user %}
{% endblock %}