DjangoBlog/DjangoBlog/urls.py
from django.contrib import admin
from django.urls import path,include
#增加站点地图
from django.contrib.sitemaps.views import sitemap
from .sitemap import StaticViewSitemap,ArticleSiteMap,CategorySiteMap,TagSiteMap,UserSiteMap
from .feeds import DjangoBlogFeed
from django.views.decorators.cache import cache_page
from django.conf import settings
from django.conf.urls.static import static

sitemaps ={
        'blog':ArticleSiteMap,
        'Category':CategorySiteMap,
        'Tag':TagSiteMap,
        'User':UserSiteMap,
        'static':StaticViewSitemap,
        }


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blog.urls',namespace ='blog')),
    #增加评论url
    path('',include('comments.urls',namespace='comments')),
    #账号相关url
    path('',include('accounts.urls',namespace='accounts')),
    path('',include('oauth.urls',namespace='oauth')),
    path('sitemap.xml',cache_page(60*60*10)(sitemap),{'sitemaps':sitemaps},name='django.contrib.sitemaps.views.sitemap'),
    path('feed/',cache_page(60*60*10)(DjangoBlogFeed())),
    #添加搜索相关功能
    path('search',include('haystack.urls'),name='search'),
    ] + static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

DjangoBlog/blog/urls.py
from django.urls import path
from . import views
from haystack.forms import ModelSearchForm
from haystack.query import SearchQuerySet
from haystack.views import SearchView
from django.views.decorators.cache import cache_page

#如果引用blog的url使用的include中指定了namespace则必须定义app_name或者在include中指定app_name
app_name ='blog'
urlpatterns  =[
    path('',views.IndexView.as_view(),name='index'),
    path('page/<page>',views.IndexView.as_view(),name='index_page'),
    path('article/<year>/<month>/<day>/<article_id>-<slug>.html',views.ArticleDetailView.as_view(),name = 'detailbyid'),
    path('category/<category_name>',views.CategoryDetailView.as_view(),name ='category_detail'),
    path('author/<author_name>',views.AuthorDetailView.as_view(),name='author_detail'),
    path('tags/<tag_name>',views.TagDetailView.as_view(),name='tag_detail'),
    path('blogpage/<year>/<month>/<day>/<page_id>-<slug>.html',views.ArticleDetailView.as_view(),name ='pagedetail'),
    path('upload',views.fileupload,name='upload'),
    path('refresh',views.refresh_memcache,name='refresh')
    ]

DjangoBlog/comments/urls.py
#!/usr/bin/env python
#encoding: utf-8
from django.urls import path
from . import views
app_name =  'comments'
urlpatterns = [
        path('article/<article_id>/postcomment',views.CommentPostView.as_view(),name='postcomment'),
        ]

DjangoBlog/comments/models.py
from django.db import models
from django.conf import settings
from blog.models import Article
from django.core.mail import send_mail
from django.core.mail import EmailMultiAlternatives
from django.contrib.sites.models import Site
import _thread
from DjangoBlog.utils import cache
# Create your models here.
#创建评论模型
class Comment(models.Model):
    body = models.TextField('正文',max_length=300)
    created_time = models.DateTimeField('创建时间',auto_now_add = True)
    last_mod_time = models.DateTimeField('修改时间',auto_now = True)
    author = models.ForeignKey(settings.AUTH_USER_MODEL,verbose_name = '作者',on_delete=models.CASCADE)

    article = models.ForeignKey(Article,verbose_name='文章',on_delete = models.CASCADE)
    parent_comment = models.ForeignKey('self',verbose_name='上级评论',blank= True,null = True,on_delete=models.CASCADE)


    class Meta:
        ordering = ['created_time']
        verbose_name = "评论"
        verbose_name_plural = verbose_name
        get_latest_by  = 'created_time'
        print("Enter Comment")

    def send_comment_email(self,msg):
        try:
            msg.send()
        except:
            pass
    def __str__(self):
        return self.body

    def save(self,*args,**kwargs):
       super().save(*args,**kwargs)
       subject = "感谢您发表的评论"
       site = Site.objects.getcurrent().domain
       article_url = "https://{site}{path}".format(site=site,path=self.article.get_absolute_url())
       html_content ="""
       <p>非常感谢您在本站发表评论</p>
       您可以访问
       <a href="%s" rel="bookmark">%s</a>
       来查看您的评论，
       再次感谢您！
       <br />
       如果上面链接无法打开，请将此链接复制至浏览器。
       %s
       """ % (article_url,self.article.tile,article_url)

       tomail = self.author.email
       msg = EmailMultiAlternatives(subject,html_content,from_email="no-reply@lylinux.net",to=[tomail])
       msg.conent_subtype ="html"

       #线程中执行
       _thread.start_new_thread(self.send_comment_email,(msg,))
       if self.parent_comment:
          html_content = """
          您在 <a href="%s" rel="bookmark">%s</a> 的评论 <br/> %s <br/> 收到回复啦.快去看看吧
          <br/>
          如果上面链接无法打开，请将此链接复制至浏览器。
          %s
          """ % (article_url,self.article.title,self.parent_comment.body,article_url)
          tomail = self.parent_comment.author.email
          msg = EmailMultiAlternatives(subject,thml_content,from_email="no_reply@lynux.net",to=[tomail])
          msg.conent_subtype ="html"
          #线程中执行
          _thread.start_new_thread(self.send_comment_email,(msg,))

    def __str__(self):
        return self.body

DjangoBlog/comments/forms.py
#!/usr/bin/env python
#encoding: utf-8
from .models import Comment
from django import forms
from django.forms import ModelForm
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model
"""
class LoginCommentForm(ModelForm):
    url = forms.URLField(label='网址',require=False)
    email = forms.EmailField(label='电子邮箱',require=False,widget=forms.HiddenInput)
    name = forms.CharField(label='姓名',widget=forms.HiddenInput)
    parent_comment_id = forms.IntegerField(widget=forms.HiddenInput,required = False)
    
    def __init__(self):
        pass

    class Meta:
        model = Comment
        fields  =['body']


class CommentForm(ModelForm):
    url =forms.URLField(label='网址',required  = False)
    if User.is_authenticated:
        email = forms.EmailField(label='电子邮箱',required  = False,widget = forms.HiddenInput)
        name = forms.CharField(label='姓名',widget   = forms.HiddenInput)
    else:
        email = forms.EmailField(label='电子邮箱',required  = False)
        name = forms.CharField(label  ='姓名')
    
    parent_comment_id = forms.IntegerField(widget=forms.HiddenInput,required  = False)
"""
class CommentForm(ModelForm):
    url  =forms.URLField(label='网址',required = False)
    if User.is_authenticated:
        email = forms.EmailField(label='电子邮箱',required = True)
        name = forms.CharField(label='姓名',widget=forms.TextInput(attrs={'value':"",'size':"30",'maxlenght':"245",'aria-required':'true'}))
        parent_comment_id = forms.IntegerField(widget=forms.HiddenInput,required  = False)

    class Meta:
        model = Comment
        fields  =['body']

DjangoBlog/comments/views.py
from django.shortcuts import render

# Create your views here.
from .models import Comment
from blog.models import Article
from .forms import CommentForm
from django.views.generic.edit import FormView
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model
from accounts.models import BlogUser
from django import forms
from django.contrib import auth

class CommentPostView(FormView):
    form_class = CommentForm
    template_name ='blog/article_detail.html'
    
    def get(self,request,*args,**kwargs):
        article_id = self.kwargs['article_id']
        article  = Article.objects.get(pk=article_id)
        url = article.get_absolute_url()
        print("文章路径url="+url)
        return HttpResponseRedirect(url + "#comments")


    def form_invalid(self,form):
        article_id  = self.kwargs['article_id']
        article = Article.objects.get(pk = article_id)
        u = self.request.user

        if self.request.user.is_authenticated:
            form.fields.update({'email':forms.CharField(widget=forms.HiddenInput()),'name':forms.CharField(widget=forms.HiddenInput())})
            user =self.request.user
            form.fields['email'].initial = user.email
            form.fields['name'].initial = user.username

        return self.render_to_response({'form':form,'article':article})

    def form_valid(self,form):
        """提交的数据验证合法后的逻辑"""
        user = self.request.user
        article_id = self.kwargs['article_id']
        article = Article.objects.get(pk=article_id)

        if not self.request.user.is_authenticated():
            comment = form.save(False)
            comment.article = article
            user = get_user_model().objects.get_or_create(username=username,email=email)[0]

        commant = form.save(False)
        comment.article = article
        comment.author = user
        
        if form.cleaned_data['parent_comment_id']:
            parent_comment = Comment.objects.get(pk  = form.cleaned_data['parent_comment_id'])
            comment.parent_comment  = parent_comment

        comment.save(True)

        from DjangoBlog.utils import expire_view_cache,cache
        from django.contrib.sites.models import Site
        path = article.get_absolute_url()
        site = Site.objects.get_current().domain

        if site.find(':')  >0:
            site =site[0:site.find(':')]

        expire_view_cache(path,servername=site,serverport=self.request.get_port(),key_prefix='blogdetail')
        if cache.get('seo_processor'):
            cache.delete('seo_processor')
        
        comment_cache_key =  'article_comments_{id}'.format(id=article_id)
        cache.delete(comment_cache_key)

        from django.core.cache.utils import make_template_fragment_key
        username = self.request.user.username if self.request.user else ''
        key = make_template_fragment_key('sidebar',[username])
        cache.delete(key)

        return HttpResponseRedirect("%s#div-comment-%d" % (article.get_absolute_url(),comment.pk))

DjangoBlog/templates/comments/tags/comment_item.html
{% load blog_tags %}
<script>console.log("这里comment_item.html")</script>
<li class="comment even thread-even depth-{{ depth }} parent" id="comment-{{ comment_item.pk }}">
    <div id="div-comment-{{ comment_item.pk }}" class="comment-body">
        <div class="comment-author vcard">
            <img alt=""
                 src="{{ comment_item.author.email|gravatar_url:150 }}"
                 srcset="{{ comment_item.author.email|gravatar_url:150 }}"
                 class="avatar avatar-96 photo" height="96" width="96"> <cite class="fn"><a rel="nofollow"
											    href="{{comment_item.author.get_absolute_url}}" rel="external nofollow"
                class="url">{{ comment_item.author.username }}</a></cite><span
                class="says">说道：</span></div>

        <div class="comment-meta commentmetadata">
            {{ comment_item.created_time }}</div>

        <p>{{ comment_item.body }}</p>

        <div class="reply"><a rel="nofollow" class="comment-reply-link"
                              href="javascript:void(0)"
                              onclick="do_reply({{ comment_item.pk }})"
                              aria-label="回复给{{ comment_item.author.username }}">回复</a></div>
    </div>

</li><!-- #comment-## -->

DjangoBlog/templates/comments/tags/comment_list.html
<section id="comments" class="themeform">
    {% load blog_tags %}
    {% load comments_tags %}
    {% comment %} <h3 class="heading">{{ comment_count }} 条回复</h3>{% endcomment %}

    <ul class="comment-tabs group">
        <li class="active"><a href="#commentlist-container"><i
                class="fa fa-comments-o"></i>评论<span>{{ comment_count }}</span></a></li>
	{% comment %}<li class=""><a href="#pinglist-container"><i class="fa fa-share"></i>引用<span>0</span></a></li>{% endcomment %}
    </ul>
    {% if article_comments %}
        <div id="commentlist-container" class="comment-tab" style="display: block;">

            <ol class="commentlist">
                {% query article_comments parent_comment=None as parent_comments %}
                {% for comment in parent_comments %}
                    {% show_comment_item comment False %}

                    {% parse_commenttree article_comments comment as childcomments %}
                    {% if childcomments %}
                        <ul class="children">
                            {% for child in childcomments %}
                                {% show_comment_item child True %}

                            {% endfor %}
                        </ul><!-- .children -->
                    {% endif %}


                {% endfor %}

            </ol><!--/.commentlist-->


        </div>

    {% endif %}
</section>

DjangoBlog/templates/comments/tags/post_comment.html
<div id="comments" class="comments-area">
    <script>console.log("这里post_comment.html")</script>
    <div id="respond" class="comment-respond">
        <h3 id="reply-title" class="comment-reply-title">发表评论
            <small><a rel="nofollow" id="cancel-comment-reply-link" href="/wordpress/?p=3786#respond"
                      style="display:none;">取消回复</a></small>
        </h3>
        <form action="{% url 'comments:postcomment' article.pk %}" method="post" id="commentform"
              class="comment-form">{% csrf_token %}
            {% comment %}<p class="comment-notes"><span id="email-notes">电子邮件地址不会被公开。</span> 必填项已用<span class="required">*</span>标注
            </p>{% endcomment %}
            <p class="comment-form-comment">
                {{ form.body.label_tag }}
                {{ form.body }}
                {{ form.body.errors }}
                {% comment %}<label for="comment">评论</label> <textarea id="comment" name="comment"
                                                                                      cols="45" rows="8"
                                                                                      maxlength="65525"
                                                                                      aria-required="true"
                                                                                      required="required"></textarea>{% endcomment %}
            </p>
            <p class="comment-form-author">
                {% if not form.name.is_hidden %}
                    {{ form.name.label_tag }}
                {% endif %}
                {{ form.name }}
                {{ form.name.errors }}
                {% comment %}<label for="author">姓名 <span class="required">*</span></label>
                <input id="author" name="author" type="text" value="" size="30" maxlength="245" aria-required='true'
                       required='required'/></p>{% endcomment %}

            <p class="comment-form-email">
                {% comment %}    <label for="email">电子邮件 <span class="required">*</span></label> <input
                    id="email" name="email" type="text" value="" size="30" maxlength="100"
                    aria-describedby="email-notes" aria-required='true' required='required'/>{% endcomment %}
                {% if not form.email.is_hidden %}
                    {{ form.email.label_tag }}
                {% endif %}
                {{ form.email }}
                {{ form.email.errors }}
            </p>
            {% comment %}<p class="comment-form-url">
                {{ form.url.label_tag }}
                {{ form.url }}
                {{ form.url.errors }}

            </p>{% endcomment %}
            {{ form.parent_comment_id }}

            <p class="form-submit"><input name="submit" type="submit" id="submit" class="submit" value="发表评论"/>
                <small class="cancel-comment" id="cancel_comment" style="display: none">
                    <a href="javascript:void(0)" id="cancel-comment-reply-link" onclick="cancel_reply()">取消回复</a>
                </small>
            </p>
        </form>
    </div><!-- #respond -->

</div><!-- #comments .comments-area -->