DjangoBlog/DjangoBlog/urls.py
from django.contrib import admin
from django.urls import path,include
#增加站点地图
from django.contrib.sitemaps.views import sitemap
from .sitemap import StaticViewSitemap,ArticleSiteMap,CategorySiteMap,TagSiteMap,UserSiteMap
from .feeds import DjangoBlogFeed
from django.views.decorators.cache import cache_page
from django.conf import settings
from django.conf.urls.static import static

sitemaps ={
        'blog':ArticleSiteMap,
        'Category':CategorySiteMap,
        'Tag':TagSiteMap,
        'User':UserSiteMap,
        'static':StaticViewSitemap,
        }


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blog.urls',namespace ='blog')),
    #增加评论url
    path('',include('comments.urls',namespace='comments')),
    #账号相关url
    path('',include('accounts.urls',namespace='accounts')),
    path('',include('oauth.urls',namespace='oauth')),
    path('sitemap.xml',cache_page(60*60*10)(sitemap),{'sitemaps':sitemaps},name='django.contrib.sitemaps.views.sitemap'),
    path('feed/',cache_page(60*60*10)(DjangoBlogFeed())),
    #添加搜索相关功能
    path('search',include('haystack.urls'),name='search'),
    ] + static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

DjangoBlog/accounts/urls.py
#!/usr/bin/env python
#encoding:utf-8
from django.urls import path
from .forms import LoginForm
from django.contrib.auth import views as auth_view
from . import views
app_name ='accounts'
urlpatterns =[
        path('login/',views.LoginView.as_view(success_url='/'),name='login',kwargs={'authentication_form':LoginForm}),
        path('register/',views.RegisterView.as_view(success_url='/'),name='register'),
        path('logout/',views.LogoutView.as_view(),name='logout')
        ]

DjangoBlog/blog/urls.py
from django.urls import path
from . import views
from haystack.forms import ModelSearchForm
from haystack.query import SearchQuerySet
from haystack.views import SearchView
from django.views.decorators.cache import cache_page

#如果引用blog的url使用的include中指定了namespace则必须定义app_name或者在include中指定app_name
app_name ='blog'
urlpatterns  =[
    path('',views.IndexView.as_view(),name='index'),
    path('page/<page>',views.IndexView.as_view(),name='index_page'),
    path('article/<year>/<month>/<day>/<article_id>-<slug>.html',views.ArticleDetailView.as_view(),name = 'detailbyid'),
    path('category/<category_name>',views.CategoryDetailView.as_view(),name ='category_detail'),
    path('author/<author_name>',views.AuthorDetailView.as_view(),name='author_detail'),
    path('tags/<tag_name>',views.TagDetailView.as_view(),name='tag_detail'),
    path('blogpage/<year>/<month>/<day>/<page_id>-<slug>.html',views.ArticleDetailView.as_view(),name ='pagedetail'),
    path('upload',views.fileupload,name='upload'),
    path('refresh',views.refresh_memcache,name='refresh')
    ]

DjangoBlog/comments/models.py
from django.db import models
from django.conf import settings
from blog.models import Article
from django.core.mail import send_mail
from django.core.mail import EmailMultiAlternatives
from django.contrib.sites.models import Site
import _thread
from DjangoBlog.utils import cache
# Create your models here.
#创建评论模型
class Comment(models.Model):
    body = models.TextField('正文',max_length=300)
    created_time = models.DateTimeField('创建时间',auto_now_add = True)
    last_mod_time = models.DateTimeField('修改时间',auto_now = True)
    author = models.ForeignKey(settings.AUTH_USER_MODEL,verbose_name = '作者',on_delete=models.CASCADE)

    article = models.ForeignKey(Article,verbose_name='文章',on_delete = models.CASCADE)
    parent_comment = models.ForeignKey('self',verbose_name='上级评论',blank= True,null = True,on_delete=models.CASCADE)


    class Meta:
        ordering = ['created_time']
        verbose_name = "评论"
        verbose_name_plural = verbose_name
        get_latest_by  = 'created_time'
        print("Enter Comment")

    def send_comment_email(self,msg):
        try:
            msg.send()
        except:
            pass
    def __str__(self):
        return self.body

    def save(self,*args,**kwargs):
       super().save(*args,**kwargs)
       subject = "感谢您发表的评论"
       site = Site.objects.getcurrent().domain
       article_url = "https://{site}{path}".format(site=site,path=self.article.get_absolute_url())
       html_content ="""
       <p>非常感谢您在本站发表评论</p>
       您可以访问
       <a href="%s" rel="bookmark">%s</a>
       来查看您的评论，
       再次感谢您！
       <br />
       如果上面链接无法打开，请将此链接复制至浏览器。
       %s
       """ % (article_url,self.article.tile,article_url)

       tomail = self.author.email
       msg = EmailMultiAlternatives(subject,html_content,from_email="no-reply@lylinux.net",to=[tomail])
       msg.conent_subtype ="html"

       #线程中执行
       _thread.start_new_thread(self.send_comment_email,(msg,))
       if self.parent_comment:
          html_content = """
          您在 <a href="%s" rel="bookmark">%s</a> 的评论 <br/> %s <br/> 收到回复啦.快去看看吧
          <br/>
          如果上面链接无法打开，请将此链接复制至浏览器。
          %s
          """ % (article_url,self.article.title,self.parent_comment.body,article_url)
          tomail = self.parent_comment.author.email
          msg = EmailMultiAlternatives(subject,thml_content,from_email="no_reply@lynux.net",to=[tomail])
          msg.conent_subtype ="html"
          #线程中执行
          _thread.start_new_thread(self.send_comment_email,(msg,))

    def __str__(self):
        return self.body

DjangoBlog/blog/forms.py
#!/usr/bin/env python
#encoding:utf-8
from haystack.forms import SearchForm
from django import forms
from .models import Article,Category
class BlogSearchForm(SearchForm):
    querydata = forms.CharField(required = True)


    def search(self):
        datas = super(BlogSearchForm,self).search()

        if not self.is_valid():
            return selfno_query_found()

        if self.cleaned_data['querydata']:
            print(self.cleaned_data['querydata'])

        return datas    

DjangoBlog/blog/views.py
from django.shortcuts import render
from blog.models import Article,Category,Tag
# Create your views here.
#View 视图主要使用Model 的模型
from django.views.generic.list import  ListView
from django.views.generic import TemplateView
from django.views.decorators.cache import cache_page
from django.views.generic.detail import DetailView
from django.conf import settings
from django.core.exceptions import ObjectDoesNotExist
#通用显示视图
#调试调用栈
import traceback
#评论相关
from django.views.generic import UpdateView
from comments.forms import CommentForm
from comments.models import Comment
from django.core.paginator import Paginator,PageNotAnInteger,EmptyPage
from django.conf import settings
from django import forms
from abc import ABCMeta,abstractmethod
from haystack.generic_views import SearchView
from blog.forms import BlogSearchForm
import datetime
from django.views.decorators.csrf import csrf_exempt
import os
from django.contrib.auth.decorators import login_required
from DjangoBlog.utils import cache,cache_decorator,logger,get_md5
from django.utils.cache import get_cache_key
from django.utils.decorators import method_decorator
from django.utils.decorators import classonlymethod
from django.http import HttpResponseRedirect
"""class SeoProcessor():
    __metaclass__ = ABCMeta

    @abstractmethod
    def get_title(self):
        pass
    
    @abstractmethod
    def get_keywords(self):
        pass

    @abstractmethod
    def get_description(self):
        pass
"""
"""class CacheTemplateView(ListView):
    @classonlymethod
    def as_view(cls,**initkwargs):
        view = super(CacheTemplateView,cls).as_view(**initkwargs)
        return cache_page(60*60*10)(view)
"""
class ArticleListView(ListView):
    #template_name 属性用于指定用哪个模板进行渲染
    template_name = 'blog/article_index.html'
    #context_object_name 用于给上下文变量取名（模板中使用）
    context_object_name   = 'article_list'
    #页面类型
    page_type =  ''
    paginate_by = settings.PAGINATE_BY
    page_kwarg ='page'
    print("ArticleListView() constructor")
    
    def get_view_cache_key(self):
        return self.request.get['pages']

    @property
    def page_number(self):
        page_kwarg = self.page_kwarg
        page = self.kwargs.get(page_kwarg) or self.request.GET.get(page_kwarg) or 1
        return page

    def get_queryset_cache_key(self):
        """
        子类重写，获得queryset的缓存key
        """
        raise  NotImplementedError()
    
    def get_queryset_data(self):

        raise NotImplementedError()

    def get_queryset_from_cache(self,cache_key):
        value =cache.get(cache_key)
        if value:
            logger.info('get view cache.key:{key}'.format(key=cache_key))
            return value
        else:
            article_list = self.get_queryset_data()
            cache.set(cache_key,article_list)
            logger.info('set view cache.key:{key}'.format(key=cache_key))
            return article_list

    def get_queryset(self):
        key = self.queryset_cache_key()
        value = self.get_queryset_from_cache(key)
        return value


    def __init__(self):
        print("ArtilceListView() __init__()")
        self.page_description =  ''

class IndexView(ArticleListView):
    print("Index() constructor")
    #template_name属性用于指定用哪个模板进行渲染
    #template_name = 'index.html'


    #context_object_name属性用于给上下文变量取名（在模板中使用该名字)
    #context_object_name = 'article_list'


    #get_queryset是覆盖ListView的方法,由父类调用
    def get_queryset(self):
        print("IndexView get_queryset() enter")
        article_list = Article.objects.filter(type='a',status='p')
        #for article in article_list:0
        #    article.body = article.body[0:settings.ARTICLE_SUB_LENGTH]

        return article_list
    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        print("get_context_data() enter")
        return context
    
    def get_queryset_data(self):
       article_list = Article.objects.filter(type='a',status='p')
       return article_list

    def get_queryset_cache_key(self):
       cache_key  =  'index_{page}'.format(page=self.page_number)
       return cache_key

class ArticleDetailView(DetailView):
    print("ArticleDetailView() enter")
    template_name =  'blog/article_detail.html'
    model = Article
    pk_url_kwarg = 'article_id'
    context_object_name  = "article"

    def get_object(self):
        print("ArticleDetailView get_object() enter")
        obj = super(ArticleDetailView,self).get_object()
        obj.viewed()
        self.object = obj
        return obj
    
    def dispatch(self,request,*args,**kwargs):
        slug = self.kwargs['slug'] if 'slug' in self.kwargs else ''
        if slug:
            obj = super(ArticleDetail,self).get_object()
            return HttpResponseRedirect(obj.get_absolute_url)
        else:
            return super(ArticleDetailView,self).dispatch(request,*args,**kwargs)

    #重写get_context_data
    def get_context_data(self,**kwargs):
        artilceid = int(self.kwargs[self.pk_url_kwarg])
        
        #评论相关
        comment_form = CommentForm()
        u = self.request.user
        if self.request.user.is_authenticated:
            comment_form.fields.update({'email':forms.CharField(widget=forms.HiddenInput()),'name':forms.CharField(widget=forms.HiddenInput()),})
            user = self.requst.user
            comment_form.fields['email'].initial  = user.email
            comment_form.fields['name'].initial  = user.username
        key ="article_comment_{}".format(articleid)
        
        article_comments = self.object.comment_list()
        print(article_comments)

        kwargs['form']  = comment_form
        kwargs['article_comments'] = article_comments
        kwargs['comment_count'] = len(article_comments) if article_comments else 0;
        #评论相关
        
        kwargs['next_article']  = self.object.next_article
        kwargs['pre_article'] = self.object.pre_article

        return super(ArticleDetail,self).get_context_data(**kwargs)

class CategoryDetailView(ArticleListView):
    print("CategoryDetailView constructor")
    page_type  ="分类目录归档"
    

    def get_queryset_data(self):
        slug  = self.kwargs['category_name']
        category = get_object_or_404(Category,slug=slug)
        categoryname = category.name
        self.categoryname = categoryname
        categorynames = list(map(lambda c:c.name,category.get_sub_categorys()))
        article_list = Article.objects.filter(category__name__in =categorynames,status='p')
        return article_list

    
    def get_queryset_cache_key(self):
        slug = self.kwargs['category_name']
        category =get_object_or_404(Category,slug=slug)
        categoryname =category.name
        self.categoryname =categoryname
        cache_key ='category_list_{categoryname}_{page}'.format(categoryname=cateforyname,page=self.page_number)
        return cache_key

    def get_queryset(self):
        slug = self.kwargs['category_name']
        category= Category.objects.get(slug=slug)
        categoryname = category.name
        self.categoryname = categoryname
        print("CateGoryDetailView get_queryset() enter")
        try:
            categoryname = categoryname.split('/')[-1]
        except:
            pass
        article_list = Article.objects.filter(category__name=categoryname,status='p')
        return article_list
    
    def get_context_data(self,**kwargs):
        #增加额外数据
        print("CategoyDetailView get_context_data() enter")
        categoryname = self.categoryname
        try:
            categoryname = categoryname.split('/')[-1]
        except:
            pass
        kwargs['page_type'] =CategoryDetailView.page_type
        kwargs['tag_name'] = categoryname
        return super(CategoryDetailView,self).get_context_data(**kwargs)

class AuthorDetailView(ArticleListView):
    page_type = '作者文章归档'
    print("AuthorDetailView constructor")
    
    def get_queryset_cache_key(self):
        author_name  = self.kwargs['author_name']
        cache_key = 'author_{author_name}_{page}'.fromat(author_name=author_name,page=self.page_number)
        return cache_key

    def get_queryset_data(self):
        print("AuthorDetailView get_queryset_data()")
        author_name = self.kwargs['author_name']
        article_list = Article.objects.filter(author__username=author_name)
        return article_list
    
    def get_context_data(self,**kwargs):
        author_name = self.kwargs['author_name']
        kwargs['page_type'] =AuthorDetailView.page_type
        kwargs['tag_name'] = author_name
        return super(AuthorDetailView,self).get_context_data(**kwargs)

class TagListView(ListView):
    print("TagListView constructor")
    template_name = ''
    context_object_name =  'tag_list'

    def get_queryset(self):
        print("TagListView get_query_set() enter")
        tags_list = []
        tags = Tag.objects.all()
        for t in tags:
            t.article_set.count()

class TagDetailView(ArticleListView):
    page_type ='分类标签归档'
    print("TagDetailView constrouctor")
    def get_queryset_data(self):
        print("TagDetailView get_queryset() enter")
        slug = self.kwargs['tag_name']
        tag = get_object_or_404(Tag,slug=slug)
        tag_name = tag.name
        self.name = tag_name
        article_list = Article.objects.filter(tags__name = tag_name)
        return article_list

    def get_queryset_cache_key(self):
        slug = self.kwargs['tag_name']
        tag = get_object_or_404(Tag,slug=slug)
        tag_name = tag.name
        self.name  =tag_name
        cache_key = 'tag_{tag_name}_{page}'.format(tag_name=tag_name,page=self.page_number)
        return cache_key

    def get_context_data(self,**kwargs):
      print("TagDetailView get_context_data()")
      tag_name = self.name
      kwargs['page_type'] = TagDetailView.page_type
      kwargs['tag_name'] = tag_name
      return super(TagDetailView,self).get_context_data(**kwargs)


#文件上传功能
@csrf_exempt
def fileupload(request):

DjangoBlog/templates/blog/tags/article_info.html
{% load blog_tags %}
<script>console.log("这里是article_info.html")</script>
<article id="post-{{ article.pk }}"
	 class="post-{{ article.pk}} post type-post status-publish format-standard hentry" itemscope itemtype="http://schema.org/Article">
    <header class="entry-header">

        <h1 class="entry-title" itemprop="name">
	   {% if isindex %}	
            <a href="{{ article.get_absolute_url }}"
               rel="bookmark">{{ article.title }}</a>

	    {% else %}
	      {{article.title}}
	      {%endif %}
        </h1>
        <div class="comments-link">
	   {%  if article.comment_status ==  "o" %}
            <a href="{{ article.get_absolute_url }}#comments"
	       class="d0s-thread-count" data-thread-key="3815" rel="nofollow"><span class="leave-reply">
		       {% if article.comment and artilce.comment_set.count %}
		       {{article.comment_set.count}}个评论
			{% else %}
			发表评论
			{% endif %}
	    </span></a>
	    {%  endif %}
            <div style="float:right">
                {{ article.views }} views
            </div>
        </div><!-- .comments-link -->
        <br/>
	{% if article.type == 'a'  %}
        {% if not isindex %}
            {% load_breadcrumb article %}
        {% endif %}
	{% endif %}
    </header><!-- .entry-header -->

    <div class="entry-content" itemprop="articleBody">
        {% if  isindex %}
            {{ article.body|custom_markdown|truncatechars_content }}
            <p class='read-more'><a
                    href=' {{ article.get_absolute_url }}'>Read more</a></p>
        {% else %}
            {{ article.body|custom_markdown }}
        {% endif %}

    </div><!-- .entry-content -->
    {% load_article_metas article user %}
</article><!-- #post -->

DjangoBlog/templates/blog/tags/article_meta_info.html
{% load blog_tags %}
<script>console.log("这里是article_meta_info.html")</script>
<footer class="entry-meta">
	本条目发布于<a href="{{ article.get_absolute_url }}" title="{% datetimeformat article.created_time %}" itemprop="datePublished" content="{% datetimeformat article.created_time %}" rel="bookmark">

    <time class="entry-date"
          datetime="{{ article.created_time }}">
        {% datetimeformat article.created_time %}</time>
</a>
	{% if article.type == 'a' %}
    。属于<a href="{{ article.category.get_absolute_url }}" rel="category tag">{{ article.category.name }}</a>分类，
    {% if article.tags.all %}
        被贴了
        
        {% for t in article.tags.all %}
	<a href="{{t.get_absolute_url }}" rel="tag">{{ t.name }}</a>
            {% if t != article.tags.all.last %}
                ，
            {% endif %}
        {% endfor %}

        标签。
    {% endif %}
    {% endif %}
    <span class="by-author">作者是<span class="author vcard"><a class="url fn n"
								href="{{article.author.get_absolute_url}}"
                                                             title="查看所有由{{ article.author.username }}发布的文章"
                                                             rel="author">
	<span itemprop="author" itemscope itemtype="http://schema.org/Person">
	<span itemprop="name" itemprop = "publisher">
        {{ article.author.username }}
	</span></span>
    </a></span>。
	{% if user.is_authenticated %}
	<a href="{{ article.get_admin_url}}">编辑</a>
	{% endif %}
    </span>
</footer><!-- .entry-meta -->

DjangoBlog/templates/blog/tags/article_pagination.html
<nav id="nav-below" class="navigation" role="navigation">
    <h3 class="assistive-text">文章导航</h3>
    {% if page_obj.has_next  and next_url%}
        <div class="nav-previous"><a
                href="{{ next_url }}"><span
                class="meta-nav">&larr;</span> 早期文章</a></div>
    {% endif %}
    {% if page_obj.has_previous and previous_url %}
        <div class="nav-next"><a href="{{ previous_url }}">较新文章
            <span
                    class="meta-nav">→</span></a>
        </div>
    {% endif %}
</nav><!-- .navigation -->

DjangoBlog/templates/blog/tags/article_tag_list.html
{% if article_tags_list %}
    <div class="panel panel-default">
        <div class="panel-heading">标签</div>
        <div class="panel-body">

            {% for url,count,tag,color in article_tags_list %}
                <a class="label label-{{ color }}" style="display: inline-block;" href="{{ url }}"
                   title="{{ tag.name }}">
                    {{ tag.name }}
                    <span class="badge">{{ count }}</span>
                </a>
            {% endfor %}

        </div>
    </div>
{% endif %}

DjangoBlog/templates/blog/tags/articletaglist.html
{% if article_tags_list %}
    <div class="panel panel-default">
        <div class="panel-heading">标签</div>
        <div class="panel-body">

            {% for url,count,tag,color in article_tags_list %}
                <a class="label label-{{ color }}" style="display: inline-block;" href="{{ url }}"
                   title="{{ tag.name }}">
                    {{ tag.name }}
                    <span class="badge">{{ count }}</span>
                </a>
            {% endfor %}

        </div>
    </div>
{% endif %}

DjangoBlog/templates/blog/tags/breadcrumb.html
<div class="breadcrumb">
    <script>console.log("这里是breadcrumb.html")</script>	
    {% for name,url in names %}
        <div itemscope itemtype="http://data-vocabulary.org/Breadcrumb">

            <a href="{{ url }}" itemprop="url">

                <span itemprop="title"> {{ name }}</span>

            </a>&nbsp;&rsaquo;

        </div>
    {% endfor %}
    {{ title }}
</div>

DjangoBlog/templates/blog/tags/sidebar.html
<div id="secondary" class="widget-area" role="complementary">
    <script>console.log("这里是sidebar.html")</script>	
    <aside id="search-2" class="widget widget_search">
        <form role="search" method="get" id="searchform" class="searchform" action="/search">
            <div>
                <label class="screen-reader-text" for="s">搜索：</label>
                <input type="text" value="" name="q" id="q"/>
                <input type="submit" id="searchsubmit" value="搜索"/>
            </div>
        </form>
    </aside>
    {% if most_read_articles %}

        <aside id="views-4" class="widget widget_views"><h3 class="widget-title">Views</h3>
            <ul>
                {% for a in most_read_articles %}
                    <li>
                        <a href="{{ a.get_absolute_url }}" title="{{ a.title }}">
                            {{ a.title }}
                        </a> - {{ a.views }} views
                    </li>
                {% endfor %}
            </ul>

        </aside>
    {% endif %}
    {% if sidebar_categorys %}
        <aside id="su_siloed_terms-2" class="widget widget_su_siloed_terms"><h3 class="widget-title">分类目录</h3>
            <ul>
                {% for c in sidebar_categorys %}
                    <li class="cat-item cat-item-184"><a href={{ c.get_absolute_url }}>{{ c.name }}</a>
                    </li>
                {% endfor %}
            </ul>
        </aside>
    {% endif %}
    {% if sidebar_comments %}
        <aside id="ds-recent-comments-4" class="widget ds-widget-recent-comments"><h3 class="widget-title">近期评论</h3>
            {% comment %}<ul class="ds-recent-comments" data-num-items="5" data-show-avatars="1" data-show-time="1"
            data-show-title="1" data-show-admin="1" data-avatar-size="30" data-excerpt-length="70"></ul>{% endcomment %}
            <ul id="recentcomments">
                {% for c in sidebar_comments %}
                    <li class="recentcomments">
                <span class="comment-author-link">
			<a href="{{ c.author.get_absolute_url  }}" rel="external"
                       class="url">{{ c.author.username }}</a></span>
                        发表在《
                        <a href="{{ c.article.get_absolute_url }}">{{ c.article.title }}</a>》
                    </li>
                {% endfor %}
            </ul>
        </aside>
    {% endif %}
    {% if recent_articles %}
        <aside id="recent-posts-2" class="widget widget_recent_entries"><h3 class="widget-title">近期文章</h3>
            <ul>

                {% for a in  recent_articles %}
                    <li><a href="{{ a.get_absolute_url }}" title="{{ a.title }}">
                        {{ a.title }}
                    </a></li>
                {% endfor %}
            </ul>
        </aside>
    {% endif %}
    {% if sidabar_links %}
        <aside id="linkcat-0" class="widget widget_links"><h3 class="widget-title">书签</h3>
            <ul class='xoxo blogroll'>
                {% for l in sidabar_links %}
                    <li>
                        <a href="{{ l.link }}" target="_blank" title="{{ l.name }}">{{ l.name }}</a>
                    </li>
                {% endfor %}

            </ul>
        </aside>
    {% endif %}
    <script>console.log(show_adsense)</script>
    {% if show_adsense %}
    	{% include 'share_layout/adsense.html' %}
    {% endif %}
    {% if sidebar_tags %}
    	<aside id="tag_cloud-2" class="widget widget_tag_cloud"><h3 class="widget-title">标签云</h3>
            <div class="tagcloud">
                {% for tag,count,size in sidebar_tags %}
                    <a href="{{ tag.get_absolute_url }}"
                       class="tag-link-{{ tag.id }} tag-link-position-{{ tag.id }}"
                       style="font-size: {{ size }}pt;" title="{{ count }}个话题"> {{ tag.name }}
                    </a>
                {% endfor %}
            </div>
        </aside>
    {% endif %}
        <aside id="text-2" class="widget widget_text"><h3 class="widget-title">欢迎您star或者fork作者本站源代码</h3>
        <div class="textwidget">

            <p><a href="https://github.com/liangliangyy/DjangoBlog" rel="nofollow"><img
                    src="https://img.shields.io/github/stars/liangliangyy/djangoblog.svg?style=social&amp;label=Star"
                    alt="GitHub stars"></a> <a href="https://github.com/liangliangyy/DjangoBlog" rel="nofollow"><img
                    src="https://img.shields.io/github/forks/liangliangyy/djangoblog.svg?style=social&amp;label=Fork"
                    alt="GitHub forks"></a></p>
        </div>
    </aside>
    <aside id="meta-2" class="widget widget_meta"><h3 class="widget-title">功能</h3>
        <ul>
            <li><a href="{{ SITE_BASE_URL }}/admin/">管理站点</a></li>
            {% if user.is_authenticated %}
                <li><a href="{% url "accounts:logout" %}">登出</a>
                </li>

            {% else %}
                <li><a href="{% url "accounts:login" %}">登录</a>
            {% endif %}

        </ul>
    </aside>
    <div id ="rocket" class ="show" title="点我返回顶部"></div>
</div><!-- #secondary -->